"""THE e2e correctness gate for the AR loop + KV cache — TEACHER-FORCED.

Why teacher-forced and NOT free-running token-match
---------------------------------------------------
The oracle ``delayed_codes`` fixture was generated by PyTorch-on-MPS in bf16; we
run MLX-on-Metal in bf16. On this 8B *top-1* MoE trunk, a non-trivial fraction of
tokens sit on a router knife-edge where MPS-bf16 and Metal-bf16 round the gate
logits just differently enough to pick a *different* expert (documented in
docs/research/00 T2: median per-token cosine >= 0.999, but ~5/66 prefill tokens
flip experts; fp32 does NOT fix it — bf16 is the oracle-matching dtype). Greedy
decoding *compounds* every such flip: one different argmax feeds a different row
back in, which shifts the next distribution, and the two trajectories diverge.
Free-running cross-framework token-match therefore collapses to ~0.03 — this is
an inherent property of greedy sampling on a cross-framework top-1 MoE, NOT a bug
in our port. The KV cache itself is proven correct independently
(test_kv_cache_equiv: cached vs full forward cosine >= 0.9999, argmax exact).

So the real correctness gate is TEACHER-FORCED: at every frame we feed the
*oracle's* code row back in (instead of our own greedy pick), which removes the
trajectory-divergence confound and measures "given the exact same history the
oracle saw, does our trunk predict the same next token?". Two assertions:

  * frame-0 argmax (all 9 codebooks) == delayed_codes[0] EXACTLY — the hard
    correctness anchor (a deterministic prefill, no compounding possible).
  * per-codebook teacher-forced agreement >= 0.85 (measured 0.872) — the
    regression guard; the residual gap is exactly the bf16 routing knife-edge.

The user listened to the free-running render and APPROVED redefining this gate as
teacher-forced + by-ear (2026-06-14): the clone is good — same words, same voice.
DO NOT "fix" this back to a free-running >= 0.99 assertion: that gate is broken by
construction (cross-framework greedy compounding), not by our code.

The by-ear smoke (test_e2e_by_ear_smoke) free-runs synthesize() and writes
outputs/e2e.wav for listening; it asserts only that finite audio frames were
produced — NO token-match assertion (intentionally; see above).

Run SERIALLY (the trunk is 8B / ~15 GB bf16) — one GPU job at a time.
"""

import numpy as np
import mlx.core as mx
import pytest
from pathlib import Path

from zonos2_mlx.generate import SamplingOptions, sample_codes
from zonos2_mlx.model import Zonos2Model
from zonos2_mlx.pipeline import synthesize
from zonos2_mlx.textnorm import build_prompt

_R = Path(__file__).resolve().parent.parent
_F = _R / "outputs/fixtures"

# Same text the oracle used to dump delayed_codes.npy.
_TEXT = "The quick brown fox jumps over the lazy dog."

# The teacher-forced agreement floor. Measured 0.872 on 2026-06-14; the residual
# gap below 1.0 is the cross-framework bf16 top-1-MoE routing knife-edge, not a
# port bug. DO NOT relax below 0.85 without re-investigating (see module docstring).
_AGREEMENT_FLOOR = 0.85


def _greedy_opts() -> SamplingOptions:
    """The EXACT sampling config the real AR loop uses on the gate path:
    temperature 0 (greedy), rep-penalty window 50 / penalty 1.2 / 8 codebooks.
    Keeping this identical to generate_audio_codes makes the per-frame argmax
    apples-to-apples with how generation actually samples."""
    return SamplingOptions(
        temperature=0.0,
        repetition_window=50,
        repetition_penalty=1.2,
        repetition_codebooks=8,
    )


@pytest.mark.gpu
def test_e2e_teacher_forced_codes_match():
    """Teacher-forced per-codebook agreement against the oracle delayed codes.

    frame-0 argmax must be EXACT; per-codebook agreement over the whole
    oracle trajectory must be >= 0.85. This is THE correctness gate.
    """
    model = Zonos2Model.from_pretrained(str(_R / "weights/zonos2-bf16"))
    cfg = model.cfg

    lda = mx.array(np.load(_F / "lda.npy").astype(np.float32))  # (1, 1024) oracle LDA
    ref = np.load(_F / "delayed_codes.npy").astype(np.int64)    # (262, 9) oracle codes
    n_frames = ref.shape[0]
    text_vocab = cfg.text_vocab

    # Build the SAME prompt the oracle used (conditioning + text prefix).
    prompt, speaker_position = build_prompt(cfg, _TEXT, has_speaker=True)
    prompt = mx.array(prompt)
    speaker_position = int(speaker_position) if speaker_position is not None else 0

    opts = _greedy_opts()

    # --- Prefill: speaker injected here only -> frame-0 logits. -------------
    caches = model.make_kv_caches(prompt.shape[1] + n_frames)
    logits = model.forward_cached(
        prompt, caches, speaker_lda=lda, speaker_position=speaker_position
    )
    mx.eval(logits, *[c.k for c in caches], *[c.v for c in caches])

    # Frame-0 greedy pick (empty history -> raw argmax after softcap), via the
    # SAME sample_codes path the loop uses so softcap/rep-penalty match.
    pred0 = sample_codes(logits, [], opts)  # (9,) int64
    frame0_exact = bool(np.array_equal(pred0, ref[0]))
    if not frame0_exact:
        bad = np.where(pred0 != ref[0])[0]
        print("frame-0 MISMATCH at codebooks", bad.tolist(),
              "pred", pred0.tolist(), "ref", ref[0].tolist())

    # --- Teacher-forced loop over t = 1 .. n_frames-1. ---------------------
    # At frame t: feed the ORACLE row delayed_codes[t-1] (+ text col), then
    # compare our greedy next-token (rep-penalty applied to the ORACLE history
    # delayed_codes[:t], exactly as the real loop would) against delayed_codes[t].
    agree = 0
    total = 0
    first_divergent: int | None = None
    n_cb = cfg.n_codebooks

    for t in range(1, n_frames):
        prev_row = ref[t - 1].astype(np.int32)  # (9,) oracle codes
        next_row = mx.array(
            np.concatenate([prev_row, [text_vocab]]).reshape(1, 1, n_cb + 1)
        )
        logits = model.forward_cached(next_row, caches)
        mx.eval(logits, *[c.k for c in caches], *[c.v for c in caches])

        # Rep-penalty history = the ORACLE codes seen so far (apples-to-apples
        # with how the real loop builds `generated`).
        history = [ref[i] for i in range(t)]
        pred = sample_codes(logits, history, opts)  # (9,)

        match = pred == ref[t]
        agree += int(match.sum())
        total += n_cb
        if first_divergent is None and not bool(match.all()):
            first_divergent = t

    agreement = agree / total if total else 0.0

    print(f"frames: {n_frames}  per-codebook agreement: {agreement:.4f} "
          f"({agree}/{total})")
    print(f"frame-0 all-9 argmax exact: {frame0_exact}")
    print(f"first frame with any codebook disagreement: {first_divergent}")

    assert frame0_exact, (
        "frame-0 argmax must match the oracle EXACTLY (deterministic prefill, "
        f"no compounding): pred {pred0.tolist()} vs ref {ref[0].tolist()}"
    )
    assert agreement >= _AGREEMENT_FLOOR, (
        f"teacher-forced per-codebook agreement {agreement:.4f} < "
        f"{_AGREEMENT_FLOOR} — the trunk regressed (this is NOT the "
        "free-running compounding effect; teacher forcing removes that)."
    )


@pytest.mark.gpu
def test_e2e_by_ear_smoke():
    """NON-gating by-ear smoke: free-run synthesize() -> outputs/e2e.wav.

    Free-running cross-framework token-match is chaotic (greedy compounding on a
    top-1 MoE — see module docstring) and is INTENTIONALLY NOT asserted here.
    We only assert that the pipeline produced > 0 frames of finite audio; the
    listenable artifact is the qualitative gate the user approved by ear.
    """
    lda = np.load(_F / "lda.npy").astype(np.float32)  # exact oracle LDA
    out_wav = _R / "outputs/e2e.wav"
    res = synthesize(
        _TEXT,
        speaker_lda=lda,
        greedy=True,
        seed=0,
        max_new_tokens=1024,
        out_wav=str(out_wav),
    )

    assert res.codes.shape[0] > 0, "synthesize produced no audio frames"
    assert res.wav is not None and res.wav.size > 0, "no waveform decoded"
    assert np.isfinite(res.wav).all(), "decoded waveform has non-finite samples"
    assert out_wav.exists(), f"by-ear render not written to {out_wav}"
    print(f"by-ear render: {res.codes.shape[0]} frames -> {out_wav} "
          f"({res.wav.size} samples)")
